"""added phone number in user

Revision ID: 48535e6334c4
Revises: aa6e11df155e
Create Date: 2023-01-28 22:30:49.332195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48535e6334c4'
down_revision = 'aa6e11df155e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
